import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Analytics } from "@vercel/analytics/react";
import FlyoutMenu from "@/components/FlyoutMenu";
import { Suspense } from "react";
import Loading from "./loading";
import { AuthOverlayProvider } from "@/components/auth/AuthOverlayContext";
import ToasterClient from "@/components/ToasterClient";
import AuthToastListener from "@/components/AuthToastListener";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthOverlayProvider>
          <FlyoutMenu />
          {children}
          <Analytics />

          <ToasterClient />
          <AuthToastListener />
        </AuthOverlayProvider>
      </body>
    </html>
  );
}
